# Generated by Django 4.0.5 on 2023-01-25 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(default='128x128.png', upload_to='category_images')),
                ('no_of_products', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='1280x960.png', upload_to='product_images')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('price', models.IntegerField(default=0)),
                ('no_of_likes', models.IntegerField(default=0)),
                ('approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('category', models.ManyToManyField(to='blog.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
